### ISSUE TITLE
Error communicating with service: Unexpected error. Response data is: Not Found

### ISSUE THREAD

**Issue by johanandren** [lightbend/sbt-whitesource#35]
Not quite sure if it is the sbt plugin or whitesource at fault here:

```
[error] sbtwhitesource.WhiteSourceException: Error communicating with service: Unexpected error. Response data is: Not Found
[error] 	at sbtwhitesource.CheckPoliciesAction.sendCheckPolicies(WhiteSource.scala:383)
[error] 	at sbtwhitesource.CheckPoliciesAction.doExecute(WhiteSource.scala:365)
[error] 	at sbtwhitesource.BaseAction.execute(WhiteSource.scala:69)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9(WhiteSourcePlugin.scala:152)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9$adapted(WhiteSourcePlugin.scala:149)
[error] 	at sbtwhitesource.WhiteSourcePlugin$$$Lambda$4940/41435773.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at scala.Function1$$Lambda$1585/1332146909.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$2471/253429336.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.Execute$$Lambda$2488/1737856078.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.Execute$$Lambda$2479/1685837139.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$2486/343115305.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] Caused by: org.whitesource.agent.client.WssServiceException: Unexpected error. Response data is: Not Found
[error] 	at org.whitesource.agent.client.WssServiceClientImpl.service(WssServiceClientImpl.java:248)
[error] 	at org.whitesource.agent.client.WssServiceClientImpl.checkPolicyCompliance(WssServiceClientImpl.java:149)
[error] 	at org.whitesource.agent.client.WhitesourceService.checkPolicyCompliance(WhitesourceService.java:216)
[error] 	at sbtwhitesource.CheckPoliciesAction.sendCheckPolicies(WhiteSource.scala:373)
[error] 	at sbtwhitesource.CheckPoliciesAction.doExecute(WhiteSource.scala:365)
[error] 	at sbtwhitesource.BaseAction.execute(WhiteSource.scala:69)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9(WhiteSourcePlugin.scala:152)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9$adapted(WhiteSourcePlugin.scala:149)
[error] 	at sbtwhitesource.WhiteSourcePlugin$$$Lambda$4940/41435773.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at scala.Function1$$Lambda$1585/1332146909.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$2471/253429336.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.Execute$$Lambda$2488/1737856078.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.Execute$$Lambda$2479/1685837139.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$2486/343115305.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] Caused by: org.apache.http.client.HttpResponseException: Not Found
[error] 	at org.apache.http.impl.client.AbstractResponseHandler.handleResponse(AbstractResponseHandler.java:69)
[error] 	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:65)
[error] 	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:51)
[error] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222)
[error] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
[error] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
[error] 	at org.whitesource.agent.client.WssServiceClientImpl.service(WssServiceClientImpl.java:221)
[error] 	at org.whitesource.agent.client.WssServiceClientImpl.checkPolicyCompliance(WssServiceClientImpl.java:149)
[error] 	at org.whitesource.agent.client.WhitesourceService.checkPolicyCompliance(WhitesourceService.java:216)
[error] 	at sbtwhitesource.CheckPoliciesAction.sendCheckPolicies(WhiteSource.scala:373)
[error] 	at sbtwhitesource.CheckPoliciesAction.doExecute(WhiteSource.scala:365)
[error] 	at sbtwhitesource.BaseAction.execute(WhiteSource.scala:69)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9(WhiteSourcePlugin.scala:152)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9$adapted(WhiteSourcePlugin.scala:149)
[error] 	at sbtwhitesource.WhiteSourcePlugin$$$Lambda$4940/41435773.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at scala.Function1$$Lambda$1585/1332146909.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$2471/253429336.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.Execute$$Lambda$2488/1737856078.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.Execute$$Lambda$2479/1685837139.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$2486/343115305.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] java.lang.RuntimeException: Error communicating with service: Unexpected error. Response data is: Not Found
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at sbtwhitesource.BaseAction.handleError(WhiteSource.scala:349)
[error] 	at sbtwhitesource.BaseAction.execute(WhiteSource.scala:71)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9(WhiteSourcePlugin.scala:152)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9$adapted(WhiteSourcePlugin.scala:149)
[error] 	at sbtwhitesource.WhiteSourcePlugin$$$Lambda$4940/41435773.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at scala.Function1$$Lambda$1585/1332146909.apply(Unknown Source)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.internal.util.$tilde$greater$$Lambda$2471/253429336.apply(Unknown Source)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.Execute$$Lambda$2488/1737856078.apply(Unknown Source)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.Execute$$Lambda$2479/1685837139.apply(Unknown Source)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.ConcurrentRestrictions$$anon$4$$Lambda$2486/343115305.apply(Unknown Source)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (whitesourceCheckPolicies) Error communicating with service: Unexpected error. Response data is: Not Found
```

**Comment by dwijnand** [comment]
one suggested way to deal with this is in #33
