### ISSUE TITLE
non-fatal missing org token shouldn't look fatal

### ISSUE THREAD

**Issue by dwijnand** [lightbend/sbt-whitesource#36]
sometimes when CI fails you look and you find this:

```
[error] Error communicating with service: Illegal arguments: Bad org token
[error] sbtwhitesource.WhiteSourceException: Error communicating with service: Illegal arguments: Bad org token
[error] 	at sbtwhitesource.CheckPoliciesAction.sendCheckPolicies(WhiteSource.scala:383)
[error] 	at sbtwhitesource.CheckPoliciesAction.doExecute(WhiteSource.scala:365)
[error] 	at sbtwhitesource.BaseAction.execute(WhiteSource.scala:69)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9(WhiteSourcePlugin.scala:152)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9$adapted(WhiteSourcePlugin.scala:149)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] Caused by: org.whitesource.agent.client.WssServiceException: Illegal arguments: Bad org token
[error] 	at org.whitesource.agent.client.WssServiceClientImpl.extractResultData(WssServiceClientImpl.java:336)
[error] 	at org.whitesource.agent.client.WssServiceClientImpl.service(WssServiceClientImpl.java:223)
[error] 	at org.whitesource.agent.client.WssServiceClientImpl.checkPolicyCompliance(WssServiceClientImpl.java:149)
[error] 	at org.whitesource.agent.client.WhitesourceService.checkPolicyCompliance(WhitesourceService.java:216)
[error] 	at sbtwhitesource.CheckPoliciesAction.sendCheckPolicies(WhiteSource.scala:373)
[error] 	at sbtwhitesource.CheckPoliciesAction.doExecute(WhiteSource.scala:365)
[error] 	at sbtwhitesource.BaseAction.execute(WhiteSource.scala:69)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9(WhiteSourcePlugin.scala:152)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9$adapted(WhiteSourcePlugin.scala:149)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
```

but you might miss that right after that is:

```
[success] Total time: 4 s, completed Mar 8, 2018 2:02:25 PM
```

the actual error might be a one-liner right below that, but the very verbose stacktrace print out make it look like the missing org token is fatal.

**Comment by dwijnand** [comment]
this just happened in https://github.com/sbt/zinc/pull/510. some references from past discussions:

* https://github.com/lagom/lagom/pull/882#issuecomment-316610902
* https://github.com/lagom/lagom/pull/820
* https://github.com/lagom/lagom/pull/838
