### ISSUE TITLE
'Multiple elements for the same key' on sbt 1.3.0

### ISSUE THREAD

**Issue by raboof** [lightbend/sbt-whitesource#58]
When running sbt-whitesource on Akka with sbt 1.3.0-RC1 (https://github.com/akka/akka/pull/26935), I get:
```
[info] Processing com.typesafe.akka:akka-coordination:2.6-SNAPSHOT
[error] java.lang.RuntimeException: Unexpected error
[error] 	at sbtwhitesource.BaseAction.execute(WhiteSource.scala:72)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9(WhiteSourcePlugin.scala:152)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9$adapted(WhiteSourcePlugin.scala:149)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:270)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:279)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:270)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.RuntimeException: Multiple elements for the same key (com.github.jnr,jffi):
[error] 	ModuleInfo(com.github.jnr,jffi,1.2.15,Some((Artifact(jffi, jar, jar, None, Vector(), Some(https://repo1.maven.org/maven2/com/github/jnr/jffi/1.2.15/jffi-1.2.15.jar), Map(artifactId -> jffi, project.parent.groupId -> org.sonatype.oss, project.parent.artifactId -> oss-parent, project.build.sourceEncoding -> UTF-8, sonatypeOssDistMgmtSnapshotsUrl -> https://oss.sonatype.org/content/repositories/snapshots/, project.version -> 1.2.15, pom.groupId -> com.github.jnr, maven.compiler.source -> 1.6, maven.compiler.target -> 1.6, maven.test.failure.ignore -> true, maven.test.skip -> true, project.parent.version -> 7, groupId -> com.github.jnr, parent.version -> 7, project.groupId -> com.github.jnr, version -> 1.2.15, pom.version -> 1.2.15, project.artifactId -> jffi, parent.groupId -> org.sonatype.oss, parent.artifactId -> oss-parent, make.exe -> make, pom.artifactId -> jffi), None),/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/jnr/jffi/1.2.15/jffi-1.2.15.jar)))
[error] 	ModuleInfo(com.github.jnr,jffi,1.2.15,Some((Artifact(jffi, jar, jar, Some(native), Vector(), Some(https://repo1.maven.org/maven2/com/github/jnr/jffi/1.2.15/jffi-1.2.15-native.jar), Map(artifactId -> jffi, project.parent.groupId -> org.sonatype.oss, project.parent.artifactId -> oss-parent, project.build.sourceEncoding -> UTF-8, sonatypeOssDistMgmtSnapshotsUrl -> https://oss.sonatype.org/content/repositories/snapshots/, project.version -> 1.2.15, pom.groupId -> com.github.jnr, maven.compiler.source -> 1.6, maven.compiler.target -> 1.6, maven.test.failure.ignore -> true, maven.test.skip -> true, project.parent.version -> 7, groupId -> com.github.jnr, parent.version -> 7, project.groupId -> com.github.jnr, version -> 1.2.15, pom.version -> 1.2.15, project.artifactId -> jffi, parent.groupId -> org.sonatype.oss, parent.artifactId -> oss-parent, make.exe -> make, pom.artifactId -> jffi), None),/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/jnr/jffi/1.2.15/jffi-1.2.15-native.jar)))
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbtwhitesource.package$KeyByAndMergeSyntax$.$anonfun$keyByAndMerge$2(package.scala:26)
[error] 	at scala.Option.getOrElse(Option.scala:138)
[error] 	at sbtwhitesource.package$KeyByAndMergeSyntax$.$anonfun$keyByAndMerge$1(package.scala:26)
[error] 	at sbtwhitesource.package$KeyByAndMergeSyntax$.$anonfun$keyByAndMerge$1$adapted(package.scala:20)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at sbtwhitesource.package$KeyByAndMergeSyntax$.keyByAndMerge$extension(package.scala:20)
[error] 	at sbtwhitesource.BaseAction.moduleInfoByGA$1(WhiteSource.scala:162)
[error] 	at sbtwhitesource.BaseAction.moduleInfos$1(WhiteSource.scala:166)
[error] 	at sbtwhitesource.BaseAction.collectDependencyStructure(WhiteSource.scala:172)
[error] 	at sbtwhitesource.BaseAction.processProject(WhiteSource.scala:147)
[error] 	at sbtwhitesource.BaseAction.$anonfun$extractProjectInfos$2(WhiteSource.scala:83)
[error] 	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
[error] 	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:662)
[error] 	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:639)
[error] 	at scala.collection.TraversableOnce.to(TraversableOnce.scala:313)
[error] 	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:311)
[error] 	at scala.collection.AbstractIterator.to(Iterator.scala:1429)
[error] 	at scala.collection.TraversableOnce.toVector(TraversableOnce.scala:309)
[error] 	at scala.collection.TraversableOnce.toVector$(TraversableOnce.scala:309)
[error] 	at scala.collection.AbstractIterator.toVector(Iterator.scala:1429)
[error] 	at sbtwhitesource.BaseAction.extractProjectInfos(WhiteSource.scala:83)
[error] 	at sbtwhitesource.CheckPoliciesAction.doExecute(WhiteSource.scala:361)
[error] 	at sbtwhitesource.BaseAction.execute(WhiteSource.scala:69)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9(WhiteSourcePlugin.scala:152)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9$adapted(WhiteSourcePlugin.scala:149)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:270)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:279)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:270)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (whitesourceCheckPolicies) Unexpected error
```

These 2 ModuleInfo's seem to be the same, but contain different artifacts: the 'normal' and the 'native' version.

Note that this is not `sbt.librarymanagement.ModuleInfo` but `sbtwhitesource.BaseAction$ModuleInfo`.

**Comment by raboof** [comment]
For 'jar' and 'bundle' we have custom logic to select the 'bundle' (https://github.com/lightbend/sbt-whitesource/blob/bff52e9aeec23d8ff7058c4bd9b407798347c6f0/src/main/scala/sbtwhitesource/WhiteSource.scala#L253), but that doesn't seem so clear-cut here. Perhaps this `Map` should really be a MultiMap?

**Comment by dwijnand** [comment]
I'm just going to discard the native module.

**Comment by dwijnand** [comment]
Btw, this is a change in behaviour from using Coursier, I'm pretty sure.  Whether it's correct or not, I'm not.

**Comment by raboof** [comment]
Hrm, this problem still occurs for me... even when recreating the test at https://github.com/akka/akka/pull/26963

Weird thing is the line numbers don't seems to correspond to the source, while lsof does seem to suggest the right jar was loaded... :confused:  

```
[error] java.lang.RuntimeException: Unexpected error
[error]         at sbtwhitesource.BaseAction.execute(WhiteSource.scala:71)
[error]         at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9(WhiteSourcePlugin.scala:153)
[error]         at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9$adapted(WhiteSourcePlugin.scala:150)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:289)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: java.lang.RuntimeException: Multiple elements for the same key (com.github.jnr,jffi):
[error]         ModuleInfo(com.github.jnr,jffi,1.2.16,Some((Artifact(jffi, jar, jar, Some(native), Vector(), Some(https://repo1.maven.org/maven2/com/github/jnr/jffi/1.2.16/jffi-1.2.16-native.jar), Map(artifactId -> jffi, project.parent.groupId -> org.sonatype.oss, project.parent.artifactId -> oss-parent, project.build.sourceEncoding -> UTF-8, sonatypeOssDistMgmtSnapshotsUrl -> https://oss.sonatype.org/content/repositories/snapshots/, project.version -> 1.2.16, pom.groupId -> com.github.jnr, maven.compiler.source -> 1.6, maven.compiler.target -> 1.6, maven.test.failure.ignore -> true, maven.test.skip -> true, project.parent.version -> 7, groupId -> com.github.jnr, parent.version -> 7, project.groupId -> com.github.jnr, version -> 1.2.16, pom.version -> 1.2.16, project.artifactId -> jffi, parent.groupId -> org.sonatype.oss, parent.artifactId -> oss-parent, make.exe -> make, pom.artifactId -> jffi), None),/home/aengelen/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/jnr/jffi/1.2.16/jffi-1.2.16-native.jar)))
[error]         ModuleInfo(com.github.jnr,jffi,1.2.16,Some((Artifact(jffi, jar, jar, None, Vector(), Some(https://repo1.maven.org/maven2/com/github/jnr/jffi/1.2.16/jffi-1.2.16.jar), Map(artifactId -> jffi, project.parent.groupId -> org.sonatype.oss, project.parent.artifactId -> oss-parent, project.build.sourceEncoding -> UTF-8, sonatypeOssDistMgmtSnapshotsUrl -> https://oss.sonatype.org/content/repositories/snapshots/, project.version -> 1.2.16, pom.groupId -> com.github.jnr, maven.compiler.source -> 1.6, maven.compiler.target -> 1.6, maven.test.failure.ignore -> true, maven.test.skip -> true, project.parent.version -> 7, groupId -> com.github.jnr, parent.version -> 7, project.groupId -> com.github.jnr, version -> 1.2.16, pom.version -> 1.2.16, project.artifactId -> jffi, parent.groupId -> org.sonatype.oss, parent.artifactId -> oss-parent, make.exe -> make, pom.artifactId -> jffi), None),/home/aengelen/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/jnr/jffi/1.2.16/jffi-1.2.16.jar)))
[error]         at scala.sys.package$.error(package.scala:30)
[error]         at sbtwhitesource.package$KeyByAndMergeSyntax$.$anonfun$keyByAndMerge$2(package.scala:26)
[error]         at scala.Option.getOrElse(Option.scala:138)
[error]         at sbtwhitesource.package$KeyByAndMergeSyntax$.$anonfun$keyByAndMerge$1(package.scala:26)
[error]         at sbtwhitesource.package$KeyByAndMergeSyntax$.$anonfun$keyByAndMerge$1$adapted(package.scala:20)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at sbtwhitesource.package$KeyByAndMergeSyntax$.keyByAndMerge$extension(package.scala:20)
[error]         at sbtwhitesource.BaseAction.moduleInfoByGA$1(WhiteSource.scala:161)
[error]         at sbtwhitesource.BaseAction.moduleInfos$1(WhiteSource.scala:165)
[error]         at sbtwhitesource.BaseAction.collectDependencyStructure(WhiteSource.scala:169)
[error]         at sbtwhitesource.BaseAction.processProject(WhiteSource.scala:146)
[error]         at sbtwhitesource.BaseAction.$anonfun$extractProjectInfos$2(WhiteSource.scala:82)
[error]         at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
[error]         at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
[error]         at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:662)
[error]         at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:639)
[error]         at scala.collection.TraversableOnce.to(TraversableOnce.scala:313)
[error]         at scala.collection.TraversableOnce.to$(TraversableOnce.scala:311)
[error]         at scala.collection.AbstractIterator.to(Iterator.scala:1429)
[error]         at scala.collection.TraversableOnce.toVector(TraversableOnce.scala:309)
[error]         at scala.collection.TraversableOnce.toVector$(TraversableOnce.scala:309)
[error]         at scala.collection.AbstractIterator.toVector(Iterator.scala:1429)
[error]         at sbtwhitesource.BaseAction.extractProjectInfos(WhiteSource.scala:82)
[error]         at sbtwhitesource.CheckPoliciesAction.doExecute(WhiteSource.scala:368)
[error]         at sbtwhitesource.BaseAction.execute(WhiteSource.scala:68)
[error]         at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9(WhiteSourcePlugin.scala:153)
[error]         at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9$adapted(WhiteSourcePlugin.scala:150)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:289)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (whitesourceCheckPolicies) Unexpected error
```

**Comment by seglo** [comment]
We're having a similar issue in Alpakka, but in this case, it's between two artifacts with the same group id and different classifiers (`native` and `complete`).  We're using `sbt-whitesource` 0.1.18 and `sbt` 1.3.7.

https://travis-ci.com/akka/alpakka/jobs/280329800#L335

```
[info] Processing com.lightbend.akka:akka-stream-alpakka-unix-domain-socket:2.0.0-M2+27-9a87c963
[error] java.lang.RuntimeException: Unexpected error
[error] 	at sbtwhitesource.BaseAction.execute(WhiteSource.scala:79)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9(WhiteSourcePlugin.scala:152)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9$adapted(WhiteSourcePlugin.scala:149)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: java.lang.RuntimeException: Multiple elements for the same key (com.github.jnr,jffi):
[error] 	ModuleInfo(com.github.jnr,jffi,1.2.17,Some((Artifact(jffi, jar, jar, Some(native), Vector(), Some(https://repo1.maven.org/maven2/com/github/jnr/jffi/1.2.17/jffi-1.2.17-native.jar), Map(), None, false),/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/jnr/jffi/1.2.17/jffi-1.2.17-native.jar)))
[error] 	ModuleInfo(com.github.jnr,jffi,1.2.17,Some((Artifact(jffi, jar, jar, Some(complete), Vector(), Some(https://repo1.maven.org/maven2/com/github/jnr/jffi/1.2.17/jffi-1.2.17-complete.jar), Map(), None, false),/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/jnr/jffi/1.2.17/jffi-1.2.17-complete.jar)))
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbtwhitesource.package$KeyByAndMergeSyntax$.$anonfun$keyByAndMerge$2(package.scala:26)
[error] 	at scala.Option.getOrElse(Option.scala:189)
[error] 	at sbtwhitesource.package$KeyByAndMergeSyntax$.$anonfun$keyByAndMerge$1(package.scala:26)
[error] 	at sbtwhitesource.package$KeyByAndMergeSyntax$.$anonfun$keyByAndMerge$1$adapted(package.scala:20)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at sbtwhitesource.package$KeyByAndMergeSyntax$.keyByAndMerge$extension(package.scala:20)
[error] 	at sbtwhitesource.BaseAction.moduleInfoByGA$1(WhiteSource.scala:169)
[error] 	at sbtwhitesource.BaseAction.moduleInfos$1(WhiteSource.scala:173)
[error] 	at sbtwhitesource.BaseAction.collectDependencyStructure(WhiteSource.scala:177)
[error] 	at sbtwhitesource.BaseAction.processProject(WhiteSource.scala:154)
[error] 	at sbtwhitesource.BaseAction.$anonfun$extractProjectInfos$2(WhiteSource.scala:90)
[error] 	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
[error] 	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:662)
[error] 	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:639)
[error] 	at scala.collection.TraversableOnce.to(TraversableOnce.scala:315)
[error] 	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:313)
[error] 	at scala.collection.AbstractIterator.to(Iterator.scala:1429)
[error] 	at scala.collection.TraversableOnce.toVector(TraversableOnce.scala:311)
[error] 	at scala.collection.TraversableOnce.toVector$(TraversableOnce.scala:311)
[error] 	at scala.collection.AbstractIterator.toVector(Iterator.scala:1429)
[error] 	at sbtwhitesource.BaseAction.extractProjectInfos(WhiteSource.scala:90)
[error] 	at sbtwhitesource.CheckPoliciesAction.doExecute(WhiteSource.scala:362)
[error] 	at sbtwhitesource.BaseAction.execute(WhiteSource.scala:76)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9(WhiteSourcePlugin.scala:152)
[error] 	at sbtwhitesource.WhiteSourcePlugin$.$anonfun$projectSettings$9$adapted(WhiteSourcePlugin.scala:149)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (whitesourceCheckPolicies) Unexpected error
```

We bring in the artifact with `complete` classifier, but something else must be bringing in `native`.

https://github.com/akka/alpakka/blob/master/project/Dependencies.scala#L443

**Comment by seglo** [comment]
Root cause? https://github.com/sbt/sbt/issues/5325
